### PR TITLE
New vignette + bug fixes

### PR DESCRIPTION
**Pull request by pepaaran**
This Pull Request includes:
- The functions `collect_drivers_sofun` and `prepare_setup_sofun` were deleted from `rsofun` and added to `ingestr`.
- Typo in README corrected (installation of devtools)
- Bug fix: Paths to individual files were wrong for ingesting WATCH-WFDEI data (wrote `//` rather than `/`)
- Vignette "Ingest P-model drivers from coordinates": Whole workflow to get `rsofun` forcing for a given location (not necessarily flux sites), format data into `p_model_drivers` format, aggregate data into an "average year of forcing" and finally run the P-model.

### CODE REVIEW

**Comment by pepaaran** [comment]
The functions `collect_drivers_sofun` and `prepare_setup_sofun` were deleted from `rsofun` and added to `ingestr`.

**Comment by pepaaran** [comment]
Corrected a bug in the ingest of WATCH-WFDEI and WFDE5 , which wrote a `//` instead of `/` in the file paths.

**Comment by pepaaran** [comment]
@stineb I added the final version for the vignette (get forcing for non-flux sites) to the pull request. The installation works for me but I couldn't run the checks locally because some need to be run in Euler. In any case, the majority of checks are passed so you probably can safely merge the PR. Thanks!

**Comment by stineb** [comment]
Thanks @pepaaran !

**Pull request merged**
